name: matto

channels:
  - conda-forge

dependencies:
  - python=3.13
  - fenics-dolfinx=0.9.0   # its PETSc includes MUMPS, used by examples/linear_elastic/input_beam_3d.py
  - mpich
  - scipy
  - matplotlib
  - pip

  - pip:
      - gmsh==4.13.1
      - meshio==5.3.5
      - pygmsh==7.1.17
